version: "3.3"
services:
  shorter:
      build:
        context: docker/app/${BUILD}
        dockerfile: Dockerfile
      working_dir: /shorter/cmd/shorter
      volumes:
          - ./shorter:/shorter
          - ~/go/pkg/mod:/go/pkg/mod
      ports:
          - "127.0.0.1:3002:${PORT}"
      env_file:
            - .env
        # depends_on:
            # - psql
    # psql:
    #     image: postgres:9.4
    #     volumes:
    #      - ./sql/schemapsql.sql:/docker-entrypoint-initdb.d/schema.sql
    #     restart: always 
    #     ports:
    #     - 5432:5432 
    #     env_file:
    #     - .env