version: "3.3"
services:
    shorter:
        build:
            context: docker/app/${BUILD}
            dockerfile: Dockerfile
        working_dir: /shorter/cmd/shorter
        volumes:
            - ./shorter:/shorter
            - ~/go/pkg/mod:/go/pkg/mod
        ports:
            - "3000:${PORT}"
        env_file:
            - .env
        depends_on:
            - psql
    web:
        build:
            context: docker/web/${BUILD}
            dockerfile: Dockerfile
        working_dir: /web/shorter-frontend
        volumes:
            - ./web/shorter-frontend:/web/shorter-frontend
            - /web/shorter-frontend/node_modules/
        ports:
            - "4200:4200"  
        env_file:
            - .env-frontend
        depends_on:
            - shorter
            - psql      
    psql:
        image: postgres:9.4
        volumes:
            - ./sql/schemapsql.sql:/docker-entrypoint-initdb.d/schema.sql
        restart: always 
        ports:
            - 5432:5432 
        env_file:
            - .env                    
    adminer:
        image: adminer
        restart: always 
        ports:
            - 8080:8080                   