version: "3.3"
services:
  psql:
    image: postgres:9.4
    volumes:
      - ./sql/schemapsql.sql:/docker-entrypoint-initdb.d/schema.sql
    restart: always 
    ports:
      - 5432:5432 
    env_file:
      - .env 